// app/layout.js
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/layout/Navbar';

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({
   variable: '--font-geist-mono',
   subsets: ['latin'],
});

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-50 text-slate-900
          dark:bg-slate-950 dark:text-slate-100`}
         >
            <header className="sticky top-0 z-50">
               <Navbar />
            </header>
            <main>{children}</main>
            <footer></footer>
         </body>
      </html>
   );
}
